jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build
      - run: dotnet test